import React from 'react'
import { Container, Row, Col } from 'react-bootstrap'
import Help from '../../../components/common/Help'
import { Link } from 'react-router-dom'

const Term = () => {
    return (
        <Container className="mt-4">
            <Row>
                <Col md={3} sm={3} className="hidden-xs">
                    <Help />
                </Col>
                <Col>
                    <Row>
                        <Col xs={12} className="mt-4 ml-1 bg-light">
                            <h3><i class="fa fa-info-circle"></i> Terms of Use </h3>
                        </Col>
                        <Col xs={12} className="mb-3 mt-4">
                            <p className="mt-2">Your use of this Web site (www.imagesbazaar.com) means you agree to the following terms of use (the "Terms of Use"). If you do not agree with these terms you should leave this Web site (the "Site") immediately, not use the files herein, and/or not subscribe to this service.</p>
                            <p className="mt-2">PLEASE READ THESE TERMS AND CONDITIONS OF USE (HEREINAFTER REFERRED TO AS "TOU") CAREFULLY. THIS AGREEMENT GOVERNS YOUR USE OF WWW.IMAGESBAZAAR.COM (HEREINAFTER REFERRED TO AS "WEBSITE"). YOUR USE OF THIS WEB SITE (WWW.IMAGESBAZAAR.COM) MEANS YOU AGREE TO THE FOLLOWING TERMS OF CONDITIONS OF USE (THE "TERMS OF USE") DESCRIBED HEREIN AND BY ALL TERMS, POLICIES AND GUIDELINES INCORPORATED BY REFERENCE. IF YOU DO NOT AGREE TO ALL OR ANY OF THESE TERMS AND CONDITIONS, DO NOT USE THIS WEBSITE, LEAVE THIS WEBSITE IMMEDIATELY, NOT USE THE FILES HEREIN, AND/OR NOT SUBSCRIBE TO THIS SERVICE.</p>
                            <p className="mt-2">By using this website, you represent and warrant that you are over the age of 18 and are lawfully able to accept these Website terms of conditions of use. If you are using the Website on behalf of any entity, you further represent and warrant that you are authorized to accept these Website terms and conditions on such entity's behalf, and that such entity agrees to indemnify MASH for violations of these Website terms and conditions.</p>
                            <p className="mt-2"> MASH may revise and update these TOU at anytime and without notice. Your continued access or use of this website after any such changes are posted will constitute your acceptance of these changes and you would be bound by the amended TOU. </p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>1. OWNERSHIP OF THE SITE AND ITS CONTENTS</h5>
                            <p className="mt-2">This Website and MASH Content are intended for customers of MASH. You may not use this Website or the MASH Content for any purpose not related to your business with MASH's Content. You are specifically prohibited from: (a) downloading, copying, or re-transmitting any or all of the Website or MASH Content without, or in violation of, a written license or agreement with MASH or ShotIndia; (b) using any data mining, robots or similar data gathering or extraction methods; (c) manipulating or otherwise displaying the Website or the MASH Content by using framing, linking, meta-tag or similar navigational technology; (d) registering, subscribing, unsubscribing, or attempting to register, subscribe, or unsubscribe any party for any MASH Content product or service if you are not expressly authorized by such party to do so; (e) using the Website or the MASH Content other than for its intended purpose. Such unauthorized use may also violate applicable laws including without limitation copyright and trademark laws, publicity and privacy laws, moral rights, and applicable communications regulations and statutes.</p>
                            <p className="mt-2">You represent and warrant that you will comply with all applicable laws and regulations, including, without limitation, those relating to the Internet, data, e-mail, copyright, trademarks, patent, privacy, and the transmission of technical data exported from India or the country in which you reside. You further warrant that you will not interfere with the security of, or otherwise abuse this Website or any system resources, services or networks connected to or accessible through this Website. You are allowed to use this Website only for lawful purposes and activities.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>2. USE OF THE WEBSITE</h5>
                            <p className="mt-2">ImagesBazaar is a collective endeavour of thousands of passionate photographers led by Sandeep Maheshwari, who is a World Record Holder in creative photography. Our team is forever on the move, to capture the essence of India for serving it to the global audience. Some other services offered by our company ranges from photography, production, coordination, art direction, location, casting, make-up to costumes and styling. We are the first Indian stock photography company to employ full time creative researchers for studying market trends and consumer needs. This ensures that the images and videos produced by our team are not just exceptional in quality but also extremely relevant.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>3. REGISTRATION DATA AND ACCOUNT SECURITY </h5>
                            <p className="mt-2">In consideration of your use of the Website, you agree to: (a) provide correct, accurate, current and complete information about you as may be prompted by any registration forms on the Website ("Registration Data"); (b) maintain and promptly update the Registration Data, and any other information you provide to MASH, to keep it accurate, current and complete; (c) maintain the security of your password and identification; (d) notify MASH immediately of any unauthorized use of your account or other breach of security; (e) accept all responsibility for any and all activities from your account; and (f) accept all risks of unauthorized access to the registration Data and any other information you provide to MASH.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>4. INTELLECTUAL PROPERTY RIGHTS </h5>
                            <p className="mt-2">MASH is the sole owner and lawful licensee of all the rights to the Website and its Content. All materials on this Website, including, but not limited to design, layout, images, text, graphics, sound, video, trade-dress, trademarks, patents (MASH Content) are the property of MASH and are protected by all the applicable laws, including, but not limited to copyright, trademark, trade-names, patents, internet domain names, data protection, IT Act, privacy and publicity rights and other similar rights and statutes. Use of any MASH Content without the express written permission and license to use is strictly prohibited. All title, ownership and intellectual property rights in the Website and its Content shall remain with MASH, its affiliates or licensor's, as the case may be and does not pass on to you or your representatives.</p>
                            <p className="mt-2"><strong>COPYRIGHT</strong><br />MASH, its licensors, its image partners and contributors, as the case may be, own all copyrights in the represented images on the Website. No ownership in any represented images shall to anyone accessing this Website and using the Content. You shall not remove any copyright or other proprietary rights notice contained in the represented Images, any related promotional materials provided on this Website. MASH prohibits any Content or any other material that infringes on any copyright, trademark, patent, and trade secret, right to privacy, right to publicity, or any other applicable law or proprietary right to be uploaded to the Website.</p>
                            <p className="mt-2">MASH respects the intellectual property rights of others, and we expect our user(s) to do the same. MASH is not an expert in your intellectual property rights, and we cannot verify that the users and contributors to the Website have rights to the Content posted by them. If you believe that any material on the Website infringes upon any copyright that you own or control, you may file a notification of such infringement with our legal department as set forth below:</p>
                            <address>
                                Mash Audio Visuals Pvt. Ltd.<br />
                                505, Aggarwal Prestige Mall,<br />

                                Plot No.2, Road No.44,<br />

                                Pitam Pura, New Delhi-110034, India<br />

                                Email :<a href="mailto:legal@imagesbazaar.com"> legal@imagesbazaar.com</a>
                            </address>
                            <p className="mt-2">MASH may give notice of a claim of copyright infringement by means of a general notice on the Website, electronic mail to a user's e-mail address and may also remove the infringing content uploaded by the user. In the event, MASH is not removing the said Content; MASH is not endorsing the sale of any such content.</p>
                            <p className="mt-2"><strong>TRADEMARKS</strong><br />MASH is the exclusive owner and holder of MASH Trademarks, <a href="https://www.imagesbazaar.com/"> www.imagesbazaar.com</a>, www.shotindia.com, www.indianfunding.com, Mash Audio Visuals or any other ShotIndia's trade names, trademarks, logos or service marks and any other slogan or design contained in the Website and otherwise used in trade (''MASH Marks''). MASH Marks shall remain the sole property of MASH, its affiliates and subsidiaries, and may not be copied, imitated or used, in whole or in part, without the prior written permission of MASH or the applicable trademark holder.  You are not allowed to use, register, or assist others in using or registering any trademarks, trade names, logos, internet domain names, or any mark or name confusingly similar to MASH Marks or belonging to ShotIndia without MASH prior written consent. You will not now or in the future contest the validity of MASH Marks nor will oppose or assist others in opposing any registration of any of the MASH Marks. You are not allowed to use any MASH Marks in connection with any of your Works. All goodwill accruing to the MASH Marks shall belong to MASH. You agree not to use MASH Marks in any manner that might tarnish, disparage, or reflect adversely on such trademarks or MASH. You agree not to use any MASH Marks or any variant thereof including misspellings as a domain name or as part of a domain name regardless of the top-level domain, or as a meta-tag, hidden text, keyword, or any other type of programming code or data. You cannot at any time, adopt or use, without MASH's prior written consent any word or marks which is similar to or likely to be confused with MASH Marks. In addition, the look and feel of the Website, including all page headers, custom graphics, button icons and scripts, is the service mark, trademark and/or trade dress of MASH and may not be copied, imitated or used, in whole or in part, without MASH's prior written permission. All other trademarks, registered trademarks, product names and company names or logos mentioned in the Website are the property of their respective owners. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier, or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by us.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>5. LINKS</h5>
                            <p className="mt-2">MASH makes no claim or representation regarding, and accepts no responsibility for, directly or indirectly, the quality, concept, nature or reliability of third-party websites accessible by hyperlink from the Website, or websites linking to our Website. Such sites are not under the control of MASH and MASH is not responsible for the contents of any linked site or any link contained in a link site, or any review, changes or updates to such sites. MASH provides these links to you only as a convenience, and the inclusion of any link does not imply affiliation, endorsement or adoption by MASH of any site or any information contained therein. When you leave our Website, you should be aware that our terms and policies no longer govern. You should review the terms and policies, including privacy and data gathering practices, of any site to which you navigate from the Website.</p>
                            <p className="mt-2">Your participation, correspondence or business dealings with any third party found on or through the Website, regarding the payment and delivery of related goods and services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such third party, and you agree that MASH shall not be responsible or liable for any loss, damage or other matters of any sort incurred as the result of any such dealings.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>6. USER CONTENT</h5>
                            <p className="mt-2">This Website may contain photographic images and content uploaded ("User Content") in which you or third parties create, post or store any content, messages, comments, materials or other items on the Website. You are solely responsible for your use of such User Content and use them at your own risk. By posting any Content on the Website, you agree not to post, upload, transmit, distribute, store, create or otherwise publish through the Website any of the following:</p>
                            <p className="mt-2">User Content that would infringe any copyright, trademark, patent, trade secret or other intellectual property and proprietary rights or contract rights of any party. By posting any User Content, you represent and warrant that you have the lawful right to transmit, distribute and reproduce such User Content;<br />
                                Any message, comment, data, information, photographic images, sound, text or other material that is unlawful, libelous, defamatory, obscene, pornographic, harmful to minors, indecent, lewd, suggestive, harassing, threatening, invasive of privacy or publicity rights, abusive, inflammatory, fraudulent or other objectionable;<br />
                                User Content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local, state, national or international law;<br />
                                User Content that impersonates any person or entity or otherwise misrepresents your affiliation with a person or entity;
                                Unsolicited promotions, political campaigning, advertising, junk mail, spam, chain letters;<br />
                                Private information of any third party, including, without limitation, addresses, phone numbers, email addresses and credit card numbers;<br />
                                Viruses, corrupted data or other harmful, disruptive or destructive files; and<br />
                                User Content that, in the sole judgment of MASH, is objectionable or which restricts or inhibits any person from using the Website or which may expose MASH or its users to any harm or liability of any type.<br />
                                Not to delete or revise any User Content posted by any third party.<br />
                                MASH takes no responsibility and assumes no liability for any User Content posted, stored or uploaded by you or any third party, or for any loss or damage thereto, nor is MASH liable for any mistakes, defamation, slander, libel, omissions, falsehoods, obscenity, pornographic you may encounter. Your use of the User Content is entirely at your own risk. As a provider of User Content, MASH is not liable for any statements, representations and User Content provided by its users. Although MASH has no obligation to screen, edit or monitor any of the User Content posted on the Website, MASH reserves the right and in its absolute discretion can remove, screen or edit any User Content posted on the website at any time and for any reason without notice. You are solely responsible for creating backup copies of the User Content posted by you on the Website at your sole cost and expense.
                                Any use of the Website or other provisions of the Website in violation of the foregoing violates these Terms and may result, in among other things, termination and suspension of your account and your rights to use the Website. You acknowledge and agree that MASH may access, use or disclose any information about you or your use of this Website, including, without limitation, any User Content, personal information and other information required to comply with the law or any legal process; protect and defend the rights or property of MASH; or to protect the safety of MASH, its affiliates, parent, their respective directors, employees, officers, customers or the public.<br />
                                If you post User Content to the Website, unless we indicate otherwise, you grant MASH and its affiliates and subsidiaries, a non-exclusive, royalty free, perpetual, irrevocable and fully sub-licensable right to use, distribute, perform and publish, translate, create derivative works from, distribute, perform and display such User Content throughout the world in any media. You grant MASH, its affiliates and subsidiaries and sub-licensees the right to use the name that you submit in connection with such Content, if they choose.<br />
                                If you post User Content to the Site, you represent and warrant that (a) you own and control all of the rights to the User Content that you post or you otherwise have the right to post such User Content to the Site; (b) the User Content is accurate and not misleading; and (c) use and posting of the User Content you supply does not violate these Site Terms and will not violate any rights of or cause injury to any person or entity.<br />

                                MASH acts as a content integrator and is not responsible for the information and Content provided by User(s) to be displayed on the Website. MASH does not have any role in development of the User Content.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>7. LIMITATION OF LIABILITY AND DISCLAIMER</h5>
                            <p className="mt-2">THIS WEBSITE AND MASH CONTENT ARE PROVIDED "AS IS" AND MASH AND ITS DIRECTORS, EMPLOYEES, CONTENT PROVIDERS, AGENTS AND AFFILIATES EXCLUDE, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ANY WARRANTY, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY OR FITNESS FOR A PARTICULAR PURPOSE. MASH WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS WEBSITE OR MASH CONTENT, OR THE UNAVAILABILITY OF THE SAME, INCLUDING, BUT NOT LIMITED TO LOST PROFITS, AND DIRECT, INDIRECT, INCIDENTAL, PUNITIVE AND CONSEQUENTIAL DAMAGES. THE FUNCTIONS EMBODIED ON OR IN THE MATERIALS OF THIS WEBSITE ARE NOT WARRANTED TO BE UNINTERRUPTED OR WITHOUT ERROR. YOU, NOT MASH, ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION DUE TO YOUR USE OF THIS WEBSITE OR THE MASH CONTENT. MASH MAKES NO WARRANTY THAT THE WEBSITE OR CONTENT IS FREE FROM INFECTION BY VIRUSES OR ANYTHING ELSE THAT HAS CONTAMINATING OR DESTRUCTIVE PROPERTIES.</p>
                            <p className="mt-2">Mash uses reasonable efforts to ensure the accuracy, correctness and reliability of the information and Content, but Mash makes no representations or warranties as to the Content posted by the User(s) as to its accuracy, correctness, reliability and any other irregularity.</p>
                            <p className="mt-2">IN NO EVENT SHALL MASH, ITS AFFILIATES, SUBSIDIARIES AND THEIR RESPECTIVE DIRECTORS, EMPLOYEES, OFFICERS, MEMBERS OR AGENTS BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THE WEBSITE, THE SERVICES, MASH IMAGE CONTENT OR THE MATERIALS CONTAINED IN OR ACCESSES THROUGH THE WEBSITE, INCLUDING WITHOUT LIMITATION ANY DAMAGES CAUSED BY OR RESULTING FROM RELIANCE BY USER ON ANY INFORMATION OBTAINED FROM MASH, OR THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES OR EMAIL, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION OR UNAUTHORIZED ACCESS TO MASH' RECORDS, PROGRAMS OR SERVICES. IN NO EVENT SHALL THE AGGREGATE LIABILITY OF MASH, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO THE USE OF THE SITE EXCEED ANY COMPENSATION YOU PAY, IF ANY, TO MASH FOR ACCESS TO OR USE OF THE WEBSITE.</p>
                            <p className="mt-2">Some jurisdictions do not permit the exclusion or limitation of implied warranties or liability for certain categories of damages. Therefore, some or all of the limitations above may not apply to you to the extent they are prohibited or superseded by state or national provisions.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>8. INDEMNIFICATION</h5>
                            <p className="mt-2">You agree to indemnify and hold MASH, its affiliates, subsidiaries and their respective directors, employees, officers and agents harmless against all claims or liability asserted against MASH arising out of or in connection with any breach by you or anyone acting on your behalf of any of the Terms and Conditions of this Agreement. You shall defend, indemnify and hold MASH, its affiliates, subsidiaries and their respective directors, employees, agents and officers harmless from all damages, liabilities and expenses (including reasonable attorney's fees and permitted and authorized costs) arising out of breach of this Agreement as a result of claims by third parties relating to your use and act relating to this Agreement or any breach of this Agreement. Such indemnification is in addition to MASH's right to terminate for a breach of the representations and warranties and is not a waiver or limitation of MASH's other rights or remedies.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>9. GOVERNING LAW AND JURISDICTION</h5>
                            <p className="mt-2">Any dispute, violation, controversy, contest or claim arising out of or relating to this Agreement or the breach, termination or validity thereof (hereinafter the "Disputes") shall be resolved amicably in the first instance. The Parties agree to meet to resolve such dispute in good faith. Should such a solution not be reached, within [30] days from the date of commencement of the dispute, difference or disagreement or such longer period of time as may be mutually agreed by the Parties in writing, such dispute, difference or disagreement shall be referred to Arbitration and shall be finally resolved through arbitration conducted by a tribunal of three arbitrators, with the right of each party to appoint an arbitrator, who in turn will appoint a Presiding Arbitrator. The Presiding Arbitrator shall pass a speaking award. Any order/directions/awards of the majority of the tribunal shall be final and binding on both the parties. The arbitration proceedings shall be in accordance with the Indian Arbitration and Conciliation Act 1996 and Rules there under as at present in force. The seat of arbitration shall be Delhi, India. The arbitration shall be administered in accordance with its practice, rules and regulations. If the award passed in the Arbitration proceeding is not acceptable to any of the Party, then the Party is free to approach the appropriate court of law as agreed herein below. This Agreement shall be construed in accordance with and governed by the laws of India without giving effect to their conflict of laws principles or rules. The courts at Delhi, India shall have exclusive Jurisdiction.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>10. TERMINATION</h5>
                            <p className="mt-2">Notwithstanding any of these Website terms and conditions, MASH reserves the right, without notice in its sole discretion, to terminate your account and/or block your use of the Website. Upon termination, you must destroy and cease to use all materials obtained from this Website, copies and related documentation thereof with immediate effect.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>11. REMEDY FOR BREACH</h5>
                            <p className="mt-2">You agree that any breach of this Agreement by you or your representatives would cause MASH irreparable harm, injury, loss and damage, the extent of which would be impossible to ascertain and for which monetary damages would not be an adequate remedy. Accordingly, in addition to any other remedies MASH may have at law or in equity, MASH shall be entitled to injunctive and other equitable relief in the event of any such breach of this Agreement by you or your representatives.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>12. SEVERABILITY</h5>
                            <p className="mt-2">If one or more of the provisions contained in this Agreement is found to be invalid, illegal or enforceable in any respect, the validity, legality and enforceability of the remaining provisions shall not be affected. Such provisions shall be revised only to the extent necessary to make them enforceable.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>13. WAIVER</h5>
                            <p className="mt-2">No action of MASH, other than express written waiver, may be construed as a waiver of any provision of this Agreement. A delay on the part of MASH of its rights or remedies will not operate as a waiver of such rights or remedies, and a single or partial exercise by a party of any such rights or remedies will not preclude other or further exercise of that right or remedy. A waiver of a right or remedy on any occasion will not be construed as a bar to or waiver of rights or remedies on any other occasion. Any rights not expressly granted herein are reserved.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>14.MASH REVERVES</h5>
                            <p className="mt-2">MASH reserves the right to change any terms and conditions contained in this Agreement or any policy or guideline of the Website, at any time and in its sole discretion. Your continued use of the Website following the posting of such changes will constitute your acceptance of such changes.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>15. CANCELLATION POLICY</h5>
                            <p className="mt-2">ImagesBazaar believes in helping its customers as far as possible, and has therefore a liberal cancellation policy. Under this policy:<br />
                                In case you feel that the product received is not as shown on the site or as per your expectations, you must bring it to the notice of our customer service within 24 hours of receiving the product. The Customer Service Team after looking into your complaint will take an appropriate decision.</p>
                        </Col>
                        <Col xs={12} className="mb-3">
                            <h5 style={{ borderBottom: "2px solid", padding: "2px", display: "inline" }}>16. REFUND POLICY</h5>
                            <p className="mt-2">If you are, for any reason, not entirely happy with your purchase, we will cheerfully issue a full refund. To request a refund, simply <Link className="text-info" to="/statics/contactus">contact us</Link> with your purchase details within ninety (90) days of your purchase. Please include your order number (sent to you via email after ordering) and optionally tell us why you're requesting a refund - we take customer feedback very seriously and use it to constantly improve our products and quality of service. Refunds are being processed within 21 days period.</p>
                        </Col>
                    </Row>

                </Col>
            </Row>
        </Container>
    )
}

export default Term